/**
 * @module saklient.cloud.resources
 */
module.exports = {
    Activity: require('./Activity'),
    Appliance: require('./Appliance'),
    Archive: require('./Archive'),
    Bridge: require('./Bridge'),
    Disk: require('./Disk'),
    DiskActivity: require('./DiskActivity'),
    DiskActivitySample: require('./DiskActivitySample'),
    DiskConfig: require('./DiskConfig'),
    DiskPlan: require('./DiskPlan'),
    FtpInfo: require('./FtpInfo'),
    Icon: require('./Icon'),
    Iface: require('./Iface'),
    IfaceActivity: require('./IfaceActivity'),
    IfaceActivitySample: require('./IfaceActivitySample'),
    Ipv4Net: require('./Ipv4Net'),
    Ipv4Range: require('./Ipv4Range'),
    Ipv6Net: require('./Ipv6Net'),
    IsoImage: require('./IsoImage'),
    LbServer: require('./LbServer'),
    LbVirtualIp: require('./LbVirtualIp'),
    License: require('./License'),
    LicenseInfo: require('./LicenseInfo'),
    LoadBalancer: require('./LoadBalancer'),
    Region: require('./Region'),
    Resource: require('./Resource'),
    Router: require('./Router'),
    RouterActivity: require('./RouterActivity'),
    RouterActivitySample: require('./RouterActivitySample'),
    RouterPlan: require('./RouterPlan'),
    Script: require('./Script'),
    Server: require('./Server'),
    ServerActivity: require('./ServerActivity'),
    ServerActivitySample: require('./ServerActivitySample'),
    ServerInstance: require('./ServerInstance'),
    ServerPlan: require('./ServerPlan'),
    Swytch: require('./Swytch'),
    VpcRouter: require('./VpcRouter')
};
