module.exports = {
    Appliance: require('./Appliance'),
    Archive: require('./Archive'),
    Disk: require('./Disk'),
    DiskConfig: require('./DiskConfig'),
    DiskPlan: require('./DiskPlan'),
    IPv6Net: require('./IPv6Net'),
    Icon: require('./Icon'),
    Iface: require('./Iface'),
    Ipv4Net: require('./Ipv4Net'),
    IsoImage: require('./IsoImage'),
    Resource: require('./Resource'),
    Router: require('./Router'),
    RouterPlan: require('./RouterPlan'),
    Script: require('./Script'),
    Server: require('./Server'),
    ServerInstance: require('./ServerInstance'),
    ServerPlan: require('./ServerPlan'),
    Swytch: require('./Swytch')
};
